name: DEV-to-MAIN

on:
  pull_request:
    branches: [ main ]  # corrected pull_request â†’ branches

permissions:
  contents: read
  packages: write # requis pour pousser sur GHCR

jobs:
  docker-test-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Docker Compose services
        working-directory: ./sample-app-master
        run: docker compose -f docker-compose.yaml up -d

      - name: Wait for services to be ready
        working-directory: ./sample-app-master
        run: |
          echo "Waiting for app to be ready..."
          timeout 180s bash -c 'until curl -f http://localhost:8081; do sleep 2; done'

